const PRODUCTS = [
  {
    "id": 1,
    "name": "Organic Hair Growth Oil",
    "slug": "organic-hair-growth-oil",
    "category": "Hair Care",
    "price": 1800,
    "oldPrice": 2200,
    "tag": "Best Seller",
    "rating": 4.9,
    "image": "assets/products/product-1.svg",
    "description": "A nourishing botanical oil blend that supports healthier-looking hair and scalp care.",
    "ingredients": "Coconut oil, castor oil, rosemary extract, almond oil, vitamin E.",
    "usage": "Massage gently into scalp 2–3 times weekly. Leave for 2 hours or overnight, then wash."
  },
  {
    "id": 2,
    "name": "Anti-Wrinkle Face Serum",
    "slug": "anti-wrinkle-face-serum",
    "category": "Skin Care",
    "price": 2200,
    "oldPrice": 2700,
    "tag": "New",
    "rating": 4.8,
    "image": "assets/products/product-2.svg",
    "description": "A lightweight facial serum formulated to support smoother-looking and glowing skin.",
    "ingredients": "Hyaluronic acid, aloe vera, rose water, vitamin C derivative.",
    "usage": "Apply 2–3 drops on clean skin at night. Use sunscreen during daytime."
  },
  {
    "id": 3,
    "name": "Organic Face Glow Cream",
    "slug": "organic-face-glow-cream",
    "category": "Skin Care",
    "price": 1600,
    "oldPrice": 1900,
    "tag": "Popular",
    "rating": 4.7,
    "image": "assets/products/product-3.svg",
    "description": "A soft daily moisturizer for fresh, hydrated, and naturally glowing-looking skin.",
    "ingredients": "Shea butter, aloe vera, almond oil, rose extract.",
    "usage": "Apply a small amount on face and neck after cleansing."
  },
  {
    "id": 4,
    "name": "Herbal Hair Mask",
    "slug": "herbal-hair-mask",
    "category": "Hair Care",
    "price": 1450,
    "oldPrice": 1700,
    "tag": "Organic",
    "rating": 4.6,
    "image": "assets/products/product-4.svg",
    "description": "A creamy herbal mask that helps hair feel softer, smoother, and more manageable.",
    "ingredients": "Amla powder, aloe vera gel, argan oil, fenugreek extract.",
    "usage": "Apply to damp hair for 20 minutes, then rinse thoroughly."
  },
  {
    "id": 5,
    "name": "Rose Hydrating Toner",
    "slug": "rose-hydrating-toner",
    "category": "Skin Care",
    "price": 950,
    "oldPrice": 1200,
    "tag": "Daily Care",
    "rating": 4.5,
    "image": "assets/products/product-5.svg",
    "description": "A refreshing rose toner that helps skin feel calm, hydrated, and balanced.",
    "ingredients": "Rose water, cucumber extract, aloe vera, glycerin.",
    "usage": "Spray or apply with cotton after cleansing, morning and night."
  },
  {
    "id": 6,
    "name": "Vitamin C Glow Drops",
    "slug": "vitamin-c-glow-drops",
    "category": "Skin Care",
    "price": 1850,
    "oldPrice": 2300,
    "tag": "Glow",
    "rating": 4.8,
    "image": "assets/products/product-6.svg",
    "description": "Brightening care drops designed to support radiant and even-looking skin tone.",
    "ingredients": "Vitamin C derivative, orange extract, hyaluronic acid, aloe vera.",
    "usage": "Apply 2 drops in the morning before moisturizer. Use sunscreen after."
  },
  {
    "id": 7,
    "name": "Aloe Soothing Gel",
    "slug": "aloe-soothing-gel",
    "category": "Skin Care",
    "price": 850,
    "oldPrice": 1050,
    "tag": "Soothing",
    "rating": 4.7,
    "image": "assets/products/product-7.svg",
    "description": "A cooling multipurpose gel for soothing and hydrating dry-feeling skin.",
    "ingredients": "Aloe vera, cucumber extract, glycerin, vitamin E.",
    "usage": "Apply to face, hands, or body whenever skin feels dry or irritated."
  },
  {
    "id": 8,
    "name": "Deep Nourish Hair Serum",
    "slug": "deep-nourish-hair-serum",
    "category": "Hair Care",
    "price": 1550,
    "oldPrice": 1850,
    "tag": "Smooth Hair",
    "rating": 4.6,
    "image": "assets/products/product-8.svg",
    "description": "A non-greasy serum that helps reduce frizz and adds a soft, polished finish.",
    "ingredients": "Argan oil, jojoba oil, vitamin E, silk protein.",
    "usage": "Use 1–2 pumps on damp or dry hair lengths. Avoid scalp if oily."
  },
  {
    "id": 9,
    "name": "Pink Clay Face Mask",
    "slug": "pink-clay-face-mask",
    "category": "Skin Care",
    "price": 1350,
    "oldPrice": 1600,
    "tag": "Clean Beauty",
    "rating": 4.6,
    "image": "assets/products/product-9.svg",
    "description": "A soft clay mask that helps skin feel fresh, smooth, and deeply cleansed.",
    "ingredients": "Pink clay, rose powder, aloe vera powder, oat extract.",
    "usage": "Apply a thin layer for 10–12 minutes. Rinse before fully dry."
  },
  {
    "id": 10,
    "name": "Brow & Lash Oil",
    "slug": "brow-lash-oil",
    "category": "Hair Care",
    "price": 1100,
    "oldPrice": 1350,
    "tag": "Care Oil",
    "rating": 4.4,
    "image": "assets/products/product-10.svg",
    "description": "A gentle oil blend for caring for brows and lashes for a fuller-looking appearance.",
    "ingredients": "Castor oil, almond oil, vitamin E, coconut oil.",
    "usage": "Apply carefully with clean spoolie at night. Avoid direct eye contact."
  },
  {
    "id": 11,
    "name": "Herbal Cleanser",
    "slug": "herbal-cleanser",
    "category": "Skin Care",
    "price": 1250,
    "oldPrice": 1500,
    "tag": "Gentle",
    "rating": 4.5,
    "image": "assets/products/product-11.svg",
    "description": "A gentle daily cleanser that removes impurities without leaving skin feeling tight.",
    "ingredients": "Aloe vera, green tea, glycerin, chamomile extract.",
    "usage": "Massage onto damp face and rinse. Use morning and evening."
  },
  {
    "id": 12,
    "name": "Scalp Care Spray",
    "slug": "scalp-care-spray",
    "category": "Hair Care",
    "price": 1300,
    "oldPrice": 1650,
    "tag": "Fresh Scalp",
    "rating": 4.5,
    "image": "assets/products/product-12.svg",
    "description": "A lightweight spray that refreshes the scalp and supports a clean hair-care routine.",
    "ingredients": "Rosemary water, peppermint extract, aloe vera, tea tree water.",
    "usage": "Spray onto scalp and massage gently. Use after wash or before styling."
  },
  {
    "id": 13,
    "name": "Night Repair Cream",
    "slug": "night-repair-cream",
    "category": "Skin Care",
    "price": 2100,
    "oldPrice": 2500,
    "tag": "Night Care",
    "rating": 4.8,
    "image": "assets/products/product-13.svg",
    "description": "A rich night cream that supports soft, hydrated, and rested-looking skin by morning.",
    "ingredients": "Peptides, shea butter, rosehip oil, aloe vera.",
    "usage": "Apply at night after serum. Use on face and neck."
  },
  {
    "id": 14,
    "name": "Beard Growth Oil",
    "slug": "beard-growth-oil",
    "category": "Hair Care",
    "price": 1750,
    "oldPrice": 2050,
    "tag": "Men Care",
    "rating": 4.4,
    "image": "assets/products/product-14.svg",
    "description": "A botanical grooming oil that helps beard hair feel softer, fuller-looking, and healthy.",
    "ingredients": "Castor oil, jojoba oil, argan oil, vitamin E.",
    "usage": "Apply 3–5 drops to beard area and massage daily."
  },
  {
    "id": 15,
    "name": "Organic Lip Balm",
    "slug": "organic-lip-balm",
    "category": "Skin Care",
    "price": 550,
    "oldPrice": 700,
    "tag": "Mini Care",
    "rating": 4.6,
    "image": "assets/products/product-15.svg",
    "description": "A soft balm that helps lips feel moisturized, smooth, and protected from dryness.",
    "ingredients": "Beeswax, shea butter, coconut oil, strawberry extract.",
    "usage": "Apply whenever lips feel dry. Reapply as needed."
  }
];
